### ISSUE TITLE
Anilist and GogoAnime

### ISSUE THREAD

**Issue by AprilBayot** [consumet/api.consumet.org#644]
### Describe the bug

Anilist and Gogo anime it's not providing a streaming link it's ONLY working for the spy x family and the others are not

### Steps to reproduce

1. I tested the other anime
2. I got the id and ready to go for streaming links
3. and yeah in gogo anime i only received nothing and the anilist is error except for the spy x family 

### Expected behavior

it should return streaming links

### Actual behavior

i got error

### Additional context

n/a

**Comment by Explorer-Person** [comment]
> ### Describe the bug
> Anilist and Gogo anime it's not providing a streaming link it's ONLY working for the spy x family and the others are not
> 
> ### Steps to reproduce
> 1. I tested the other anime
> 2. I got the id and ready to go for streaming links
> 3. and yeah in gogo anime i only received nothing and the anilist is error except for the spy x family
> 
> ### Expected behavior
> it should return streaming links
> 
> ### Actual behavior
> i got error
> 
> ### Additional context
> n/a



---



Could you provide more details about the issue you faced?  

1. **Request Details**  
   - Could you share the specific requests where you encountered the error?  
   - What anime ID or name did you use in the request?  

2. **API Setup and Testing Environment**  
   - Where did you set up and test this API? For example: Heroku, Render, Railway, locally, or other platforms?

---

**Sample Requests:**  
- **Search for Anime:**  
  `https://api.consumet.org/anime/gogoanime/rezero`  
- **Retrieve Anime Info (including episodes):**  
  `https://api.consumet.org/anime/gogoanime/info/rezero-kara-hajimeru-isekai-seikatsu-2nd-season`  
- **Get Stream Links for an Episode:**  
  `https://api.consumet.org/anime/gogoanime/watch/rezero-kara-hajimeru-isekai-seikatsu-2nd-season-episode-2`  

---
more info: https://docs.consumet.org/rest-api/Anime/gogoanime/get-anime-episode-streaming-links

**Comment by AprilBayot** [comment]
Could you share the specific requests where you encountered the error?

For the streaming link of gogoanime the rest of gogoanime is fine 

What anime ID or name did you use in the request?

it's dandan and other anime id I've tested but none of them work unlike the spy x family and the api was hosted on vercel

**Comment by tushitgrg** [comment]
same issue

**Comment by Explorer-Person** [comment]
> Could you share the specific requests where you encountered the error?
> 
> For the streaming link of gogoanime the rest of gogoanime is fine
> 
> What anime ID or name did you use in the request?
> 
> it's dandan and other anime id I've tested but none of them work unlike the spy x family and the api was hosted on vercel

I understand. Could you try again or perhaps re-deploy the API on Vercel? I tested it but didn’t encounter any issues with the other anime titles. If you configured the API during deployment, which settings did you use? Or is it using the default settings?

Regarding "Dandan" not being found, the issue seems to be with the API provider, https://anitaku.bz/. The consumet.org API fetches Gogoanime data from this source. You can confirm by testing your input directly on their site—if it’s available there, it should also be accessible through the consumet API.

Some tested scenarios: 

1.
request --> https://{my-vercel-url}/anime/gogoanime/darwin
response --> 
![image](https://github.com/user-attachments/assets/eeefa175-9fb0-4187-b73e-c06bd17e3594)

2.
request --> https://{my-vercel-url}/anime/gogoanime/slayer
response --> 
![image](https://github.com/user-attachments/assets/629e24cc-b634-41e8-b5cb-01748e910b47)

3.
request --> https://{my-vercel-url}/anime/gogoanime/info/darwins-game
response --> 
![image](https://github.com/user-attachments/assets/418e36b6-ee33-41d0-80ab-0f0e5f83777a)

4. 
request --> https://{my-vercel-url}/anime/gogoanime/watch/darwins-game-episode-1
response --> 
![image](https://github.com/user-attachments/assets/fda5b275-2bfe-4e8a-8dcc-8a0faf8f278d)

5.
request --> https://{my-vercel-url}/meta/anilist/info/105190
response --> 
![image](https://github.com/user-attachments/assets/4d001a88-5874-47b2-93b2-681a35c5dfc5)


I received similar successful results with other animes in both gogoanime and anilist, also i deployed on vercel as default without setting anything. Maybe re-deploying API on Vercel would solve your errors.

**Comment by Explorer-Person** [comment]
> same issue, gogoanime and anilist is not updating episodes, for eg, dandadan ep 9 and ep10 are still not added.

Yeah, I agree—I got the same result. The issue seems to be related to the API configuration. The consumet.ts script appears to use https://anify.eltik.cc/ and supports multiple providers like "Gogoanime", "Zoro", and "Animepahe". You can view the full list of supported providers under the "mappings" section in "https://{your-confed-url}/meta/anilist/info/:id".

here: 
![image](https://github.com/user-attachments/assets/9c12ad40-fbc9-43af-aa02-fc05f54b3fdb)


By default, consumet uses Gogoanime as the provider via Anify. You might resolve the issue by specifying a different provider in the URL. For example:

Sample query:
https://{your.configured.url}/meta/anilist/info/171018?provider=zoro

For updated episodes, you can manually check each provider for specific anime. For "Dandadan," I couldn’t find episodes 9-10 either. Also "animepahe" provider not work. I will look again in the future for this issue.

**Comment by kurays015** [comment]
Why the m3u8 reponse is broken/not playing in the /watch endpoint?

**Comment by AprilBayot** [comment]
solve

**Comment by kurays015** [comment]
> solve

How did you fix the m3u8 response in /watch endpoint? mine is not even playing when tested on m3u8 player

**Comment by shimizudev** [comment]
Gogoanime is kinda dead fyi, the episodes aren't updating and zoro should be fixed now
